### PR TITLE
Enable code coverage

### PR DESCRIPTION
**Pull request by eric-wieser**
Which is sent to https://codecov.io/gh, where some sign up might be needed

### CODE REVIEW

**Comment by eric-wieser** [comment]
Result: https://codecov.io/gh/haypo/bytecode/tree/0608d6fdb329d91f1bba0320e98df392b7e34e8a

**Comment by MatthieuDartiailh** [comment]
Out of curiosity what are the advantages of using shields.io ?

**Comment by eric-wieser** [comment]
Font size, badge color, and padding is identical across all badges

**Comment by MatthieuDartiailh** [comment]
This looks good to me and is useful to have. May I merge this @haypo ?

**Comment by MatthieuDartiailh** [comment]
It may be better to ignore coverage of tests folder ? what do you think @eric-wieser ?

**Comment by eric-wieser** [comment]
Some comments on that are [here](https://softwareengineering.stackexchange.com/questions/309015/when-does-it-make-sense-to-include-test-code-in-coverage).

I'd argue this is better as it is, since it highlights which bits of the test code are not actually being run (like `WORDCODE` and most of `tests/__init__.py`)

**Comment by haypo** [comment]
I dislike code coverage. I don't see how it is useful to a project.

But I'm not opposed to the change, it's up to you.

**Comment by MatthieuDartiailh** [comment]
Code coverage is not a panacea but it can help identify untested part of the code. 100% coverage does not mean everything is perfect but it is better than a low coverage. For the project as it is now it does not bring much but (as the misses are not terrible but some could be fixed for example in concrete  _assemble_lnotab does not test the handling of large doff and dlineno) but it is an help to the review process of pull request.
For the above reason and since you are not opposed I am going to merge.

**Pull request merged**
