### PR TITLE
Add stack depth computation

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
Add stack depth computation based on byteplay implementation. The implementation take some margin with the stack depth (depth is always increased by 6 at the end). This comes from the byteplay implementation. @serprex may know more about this.
I had to modify some tests because the bytecode could not allow computation of the stack depth. I had no way to run the tests on Python 3.6 so the value of the wordcode should be specially checked.

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
I have not removed the _stacksize attribute. What should I do of this attribute ? Should stacksize be a property ?

**Comment by serprex** [comment]
Note there's an important property in byteplay: the stack size only needs to be consistent for backwards jumps. Forward jumps can take the max stack size. This is important for some specialized bytecode outputs where otherwise unnecessary POPs need to be emitted. In byteplay I only implemented this for blocks of instructions before RETURN_VALUE

The _stacksize could be used if inconsistent bytecode is found. Default to None & throw if is None. Otherwise bytecode can't be used for something like [funge.py](https://github.com/serprex/Befunge/blob/master/funge.py)

PS you misspelt 'boytecode' in comment

**Comment by MatthieuDartiailh** [comment]
I switched to tuples or even using append for speed and added some more comments.

Could you expand a bit more on the funge.py issue, why would bytecode fail to compute the stack size ? I would like @haypo opinion about using _stacksize, as it probably should not be used if the byte code was obtained from real code and edited before being re-converted.

@serprex could comment briefly on the extra safety at the end of adding 6 systematically to the computed stack size ? Is this mandatory or something that should be fixed ?

**Comment by serprex** [comment]
It should probably be fixed, I myself am not responsible for that particular constant. [CPython](https://hg.python.org/cpython/file/tip/Python/compile.c#l4883) doesn't seem to do it. Honestly byteplay's stack depth calculation code probably needs to be rewritten

funge.py compiles befunge code into python bytecode. It uses the python stack as the befunge stack. It includes instructions to avoid stack underflow as in Python that's undefined (as in, C level undefined) & in Befunge an empty stack pops as 0. The issue is that this means there's arbitrary stack usage, since that's how Befunge works. So I just pass in a stack size of 65536

**Comment by haypo** [comment]
Remarks:
* It seems like your code works on a control flow graph without using explicitly a CFG. Would it make sense to reuse ControlFlowGraph object to not have to detect basic blocks?
* Please write unit tests
* You should document your enhancement somewhere in doc/
* Would it make sense to have a stack effect method on Instr?
* Would it make sense to make compute_stacksize() public? Just document that it's slow :-)
* The code seems quite long. Maybe it deserves its own .py file?
* What is the logging thing? Is it just for debug purpose? Would it be useful to provide these logs to users?

I don't know what to think about the giant patch. I hesitate between requesting a perfect patch addressing all my comments, or accept it and then request enhancements.

At least, unit tests are required to check later that refactoring doesn't break anything.

**Comment by MatthieuDartiailh** [comment]
Thanks for the feedback @haypo. 
Actually I am looking at the CPython implementation pointed out by @serprex which is much more concise and general (it appears mostly identical for Python 2 and 3). So please do not merge now. And you are indeed right in that it works on a CFG so I think porting from C may be quite straighforward using ControlFlowGraph.
I will try to re-write the stack depth computation with those ideas in mind, furthermore by having an implementation closer to CPython it will be much easier to write unit tests (currently the stack depth is often overestimated).

Other points : 
- when I am happier with the code I will add docs
- I think having stack_effect **property** (the name fits a property better) on Instr would make sense and I will add it
- we can have compute_stacksize be public (I will make it so), but what should we do of _stacksize ? What is your opinion about @serprex suggestions (fall back is compute_stacksize fail, use it if specified without recomputing) ?
- depending on my next implementation we can decide whether or not to move the code.

**Comment by haypo** [comment]
> What is your opinion about @serprex suggestions (fall back is compute_stacksize fail, use it if specified without recomputing) ?

I propose to remove ConcreteBytecode._stacksize.

This attribute was a "temporary" hack before implementing compute_stacksize(). See to_code():

```
                              # FIXME: compute stack size
                              self._stacksize,
```

If someone really wants to get a specific stacksize, it's easy to call to_code() and then create a new code object to override the co_stacksize attribute.

**Comment by serprex** [comment]
It isn't easy to call to_code because the code'll throw on non trivial cases

**Comment by MatthieuDartiailh** [comment]
Closing in favor of #8

**Pull request closed without merging**
